import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export function InsightCard({ insight }: { insight: string }) {
  const paragraphs = insight.split(/\n\s*\n/).filter(Boolean);
  return (
    <Card>
      <CardHeader>
        <CardTitle>4. Insight</CardTitle>
        <CardDescription>Generated by Claude</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex gap-3">
          <div className="flex h-8 w-8 flex-none items-center justify-center rounded-md border border-[hsl(203,55%,18%)] bg-accent-tint font-semibold text-accent">✦</div>
          <div className="space-y-3">
            <div className="text-[11px] uppercase tracking-wider text-muted">Summary</div>
            {paragraphs.map((p, i) => (
              <p key={i} className="text-sm leading-relaxed text-ink-soft">{p}</p>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
